# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /posts/:slug
# relative_permalinks: true # this seems to break things with the version of jekyll I'm using

# Setup
title:               ğŸ‘¨ğŸ½â€ğŸ’» Roshan Sadanani
tagline:             ''
description:         'ğŸ‘‹ğŸ½ - I''m Roshan. I (am starting to) write about tech, projects, and other things I find interesting. You can follow me on twitter <a href="{{ site.author.twitter }}" target="_blank">@blattus</a>.'
url:                 http://www.roshansadanani.com
baseurl:             ''
paginate:            5
gems:               [jekyll-paginate] # needed to support post pagination
excerpt_separator:  <!--more-->

# About/contact
author:
  name:              Roshan Sadanani
  keybase:           https://keybase.io/roshans
  twitter:           https://twitter.com/blattus
  github:            https://github.com/blattus
  lastfm:            https://www.last.fm/user/blattus
  goodreads:         https://www.goodreads.com/user/show/3406351-roshan-sadanani
  trakt:             https://trakt.tv/users/blattus
  email:             ''

# Custom vars
version:             1.0.0
